### PR TITLE
Backport PR #75 & #76 to 0.10

### PR DESCRIPTION
**Pull request by fengalin**
See https://github.com/sdroege/gstreamer-rs/pull/75 & https://github.com/sdroege/gstreamer-rs/pull/76

### CODE REVIEW

**Comment by fengalin** [comment]
Any other branches you want to backport to?

**Comment by sdroege** [comment]
Only 0.10, thanks :) I would also have to check if there are any other changes to backport from master since last time I did that.

**Comment by sdroege** [comment]
I might prefer to only take the first commit, it's a lot of churn to also backport the others, and it's mostly cleanup anyway.

**Comment by sdroege** [comment]
I took that one commit now, and leave the others for 0.11/master :) That will be released soon enough anyway

Another thing for the future, please try to keep line lengths in commit messages. A bit more than 80 characters is ok, but not always and not that much :)

**Comment by fengalin** [comment]
> Another thing for the future, please try to keep line lengths in commit messages. A bit more than 80 characters is ok, but not always and not that much :)

Sorry about that. My editor is configured for [rust-fmt defaults](https://github.com/rust-lang-nursery/rustfmt/blob/master/Configurations.md#max_width) for Rust. Maybe we should add a `rustfmt.toml` to enforce line width to 80. I can do that if you want me to.

**Comment by sdroege** [comment]
Oh it's only about the commit messages. The code is fine, I use the rustfmt defaults too

**Comment by fengalin** [comment]
' misread your comment. My bad!

**Pull request closed without merging**
